application:
  version: @project.version@

server:
  port: ${SERVER_PORT:8083}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/orders}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:12345}
  jpa:
    hibernate:
      ddl-auto: update

management:
  server:
    port: ${METRICS_PORT:8090}
  endpoints:
    web:
      exposure:
        include: *
  endpoint:
    prometheus:
      access: unrestricted
  prometheus:
    metrics:
      export:
        enabled: true
