application:
  version: 1.0.0

server:
  port: ${SERVER_PORT:8083}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/mag-service?serverTimezone=UTC}
    username: ${DB_USERNAME:test}
    password: ${DB_PASSWORD:test}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  server:
    port: ${METRICS_PORT:8090}
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      access: unrestricted
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.hibernate.SQL: DEBUG